require 'pry-byebug'
require 'date'
require 'yaml'
require 'linguistics'
require 'faker'
require 'fileutils'
require 'i18n'

require_relative 'config'
require './errors/errors'
require './mixins/random_creatable'
require './mixins/property_validatable'
require './classes/author'
require './classes/book'
require './classes/order'
require './classes/reader'
require './classes/library'
